### ISSUE TITLE
Essence-Theme is not fully responsive

### ISSUE THREAD

**Issue by steinhmor** [WonderCMS/wondercms#229]
The Essence Theme looks strange on smaller displays.

![grafik](https://user-images.githubusercontent.com/11630531/105645167-2db8ea80-5e9a-11eb-8364-8190583e4001.png)
![grafik](https://user-images.githubusercontent.com/11630531/105645175-37dae900-5e9a-11eb-8632-ce211aaaf916.png)
![grafik](https://user-images.githubusercontent.com/11630531/105645181-3e696080-5e9a-11eb-8266-656ad04c620c.png)

**Comment by steinhmor** [comment]
This only happens with too long texts in the Extra editable area

**Comment by robiso** [comment]
@steinhmor thank you for the report and screenshots, we'll check it out.

**Comment by robiso** [comment]
@steinhmor this has now been fixed with latest Essence theme update. :)
