### ISSUE TITLE
PHP 8.1+ support

### ISSUE THREAD

**Issue by DmitryRS** [WonderCMS/wondercms#268]
Deprecated: reset(): Calling reset() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2201
Deprecated: key(): Calling key() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2202
Deprecated: end(): Calling end() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2203
Deprecated: key(): Calling key() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2204
Deprecated: reset(): Calling reset() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2454
Deprecated: key(): Calling key() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2455
Deprecated: end(): Calling end() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2456
Deprecated: key(): Calling key() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2457
Deprecated: reset(): Calling reset() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2454
Deprecated: key(): Calling key() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2455
Deprecated: end(): Calling end() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2456
Deprecated: key(): Calling key() on an object is deprecated in C:\OpenServer\domains\wonder\index.php on line 2457

https://www.php.net/manual/en/function.reset.php
8.1.0 - Calling this function on objects is deprecated. Either use get_mangled_object_vars() on the object first, or use ArrayIterator

**Comment by robiso** [comment]
Hello @DmitryRS, thanks for the report.
Since only the error logs are filling up and WonderCMS is still functioning normally, we plan on releasing full PHP 8.2 support by the end of year (PHP 8.2 should be released in November 24).

If we currently do the upgrade, we would break about 10-20% of our user base (WonderCMS would stop functioning for them).

Keep this issue and renaming it to PHP 8.2 support.

Thanks again!

**Comment by Torsten-K** [comment]
In my case, WonderCMS 3.3.4 works under PHP 8.1 and also 8.2 on an Apache HTTP server.
