### ISSUE TITLE
Can't add picture through Summernote

### ISSUE THREAD

**Issue by Anarky** [WonderCMS/wondercms#282]
Hello, I'm not sure if it's an issue from WonderCMS or Summernote, feel free to close this one.

With a new installation of WonderCMS with Summernote enabled, if I try to insert a picture nothing is uploaded inside the `data/files` folder of the server.
It does work if I'm using the Settings > Files menu.

Tested with 3.3.4 and 3.4.0 (both affected) on two different servers.

**Comment by robiso** [comment]
Hello @Anarky, if you open up your browser "Inspect" feature activated by a right click on your website:
- do you see any errors in the console log when drag and dropping image into the Summernote editor?

**Comment by Anarky** [comment]
Hello @robiso, I don't see any errors in the console log, I tested with Firefox and Chromium. Also nothing if I look inside `/var/log/apache2/error.log`.

It does add an `<img>` tag, which the browser display with a broken logo because the `src` doesn't exist.

By the way, I have the issue both using drag and drop and with the "picture" button on the toolbar.

**Comment by robiso** [comment]
@Anarky thanks for reporting back. After further debugging this might seem like a more spread issue, not just a problem with your setup.

Me and @slavenstancic are planning to look into this today.

Can you please specify which version of PHP you're running?

**Comment by Anarky** [comment]
@robiso thank you!

Both servers are running PHP 7.4 (7.4.33 and 7.4.29).

**Comment by robiso** [comment]
@Anarky a new version of Summernote editor (3.4.1) has been released.

You can login to your WonderCMS website, open settings, click check for updates and update the Summernote plugin.
Thank you for reporting this bug.

As a token of appreciation, we'd love to add you to our list of contributors linked here: https://wondercms.com/contribute 
- Can you please post your first/last name and website, so we can link to it?

**Comment by Anarky** [comment]
Thank you for this fix, it works perfectly!
You don't need to add me to the list of contributors, don't worry.

**Comment by robiso** [comment]
Happy to hear it works, credit goes to you for reporting it so other users don't have to experience it.
You can stay anonymous with just a nickname or link to your website, you've definitely earned it. 🎖️

**Comment by joetomasone** [comment]
The old plugin is still installed on the Demo site.  I ran into this very issue trying the demo out.
