### ISSUE TITLE
Blank pages after changing theme (DOMDocument not found in...functions:30)

### ISSUE THREAD

**Issue by Entheologian** [WonderCMS/wondercms#283]
Hi,

Fresh install on a test system and when I change the theme, the page goes blank (all white) and I can't do anything. The nginx logs then show errors, such as this:

  thrown in /var/www/html/themes/parallax/functions.php on line 30" while reading response header from upstream, client: 192.168.0.100, server: vdebby, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "vdebby"
2023/01/21 10:46:26 [error] 39457#39457: *19 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/html/themes/parallax/functions.php:30
Stack trace:
#0 /var/www/html/index.php(1150): alterAdmin()
#1 /var/www/html/index.php(2337): Wcms->hook()
#2 /var/www/html/themes/parallax/theme.php(59): Wcms->settings()
#3 /var/www/html/index.php(1628): require_once('/var/www/html/t...')
#4 /var/www/html/index.php(183): Wcms->loadThemeAndFunctions()
#5 /var/www/html/index.php(16): Wcms->render()
#6 {main}
  thrown in /var/www/html/themes/parallax/functions.php on line 30" while reading response header from upstream, client: 192.168.0.100, server: vdebby, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "vdebby", referrer: "http://vdebby/"

**Comment by robiso** [comment]
Hello @Entheologian.

Looks like this theme requires the DOM extension for PHP. Depending on the system you use, this should be fairly easy to do:
- https://www.php.net/manual/en/intro.dom.php
- https://www.php.net/manual/en/class.domdocument.php

If you're stuck on blank pages and can't change the theme, you can open up the data/database.js folder and change the defaultTheme manually to another one so you can continue using WonderCMS without blank pages.

**Comment by robiso** [comment]
@Entheologian closing issue since this can be fixed my enabling the module mentioned above. If you need any help please feel free to continue commenting and we'll respond.

Closing issue for now.
