### ISSUE TITLE
Plugin/Theme install/uninstall button links contain %5c

### ISSUE THREAD

**Issue by foobass** [WonderCMS/wondercms#290]
WonderCMS v3.4.1
Windows 11
Apache 2.4.54.2
php 8.2.0

The install/uninstall Theme/Plugin buttons don't work in my installation because the urls for the links associated with these buttons contain "%5C". 

Examples: 
[code]https://wonder.test%5C/?deleteModule=sky&type=themes&token=...[/code]
[code]https://wonder.test%5C/?installModule=https://github.com/robiso/essence/archive/master.zip&directoryName=essence&type=themes&token=...[/code]

I believe %5C is an encoded backslash, so perhaps somewhere WonderCMS is escaping the forward slash in the url string?

I got things to install/uninstall by removing the %5C from the url.

Example:
[code]https://wonder.test/?deleteModule=sky&type=themes&token=...[/code]
[code]https://wonder.test/?installModule=https://github.com/robiso/essence/archive/master.zip&directoryName=essence&type=themes&token=...[/code]

But then I got some php Notices:
Deprecated: str_ireplace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in ...index.php on line 906

 Deprecated: str_ireplace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in ...index.php on line 911

Warning: Cannot modify header information - headers already sent by (output started at ...index.php:911) in ...index.php on line 2046

**Comment by robiso** [comment]
Hello @foobass, thanks for dropping by!

We intentionally strip the %5C to avoid any directory traversal.
Is there any specific reason your setup uses those?

**Comment by foobass** [comment]
I'm sorry for the misunderstanding. I did not do anything to add %5C to the urls. They are just there. I will try to track down where they come from.

**Comment by foobass** [comment]
Inside the function url() on line 2800 of index.php I added a bit of code to write dirname($_SERVER['SCRIPT_NAME']) to a log.
The logfile contains many backslashes.  Here is the copy/pasted data:

`\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\`

Also, there are many backslashes in the urls in cache.json. Not sure if it's a Windows thing at this point. Will try to investigate further.

**Comment by foobass** [comment]
Aparently dirname returns backslashes on Windows so I guess that's the issue there.

But something is also escaping forward slashes. Here is an example of a url in my cache.json file:
`"repo": "https:\/\/github.com\/robiso\/summernote-editor\/tree\/master",`

The JSON spec says you CAN escape forward slashes, but you don't have to.

**Comment by foobass** [comment]
This fixed my original problem with being able to install/uninstall plugins/themes
inside function url() on line 2800:

```
$dir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME']));

return ($showHttps ? 'https' : 'http')
. '://' . ($_SERVER['HTTP_HOST'] ?? $_SERVER['SERVER_NAME'])
. ($_SERVER['HTTP_HOST'] ? '' : $serverPort)
. ((dirname($_SERVER['SCRIPT_NAME']) === '/') ? '' : $dir)
. '/' . $location;
```
