### ISSUE TITLE
Default language of site

### ISSUE THREAD

**Issue by joho1968** [WonderCMS/wondercms#296]
It'd be nice if there was a config (or database) option for "siteLanguage", which is output in the <html> tag at the top of pages. I don't know if this is managed "automagically" by translations, but I may want to use the English (default) interface, but output most of my pages in Swedish, in which case it'd be nice if I could put "sv" as the "siteLanguage".

**Comment by WebCrew** [comment]
Same here, I also prefer to use the default admin interface in english but my website content in german - so I'm happy to agree with @joho1968 suggestion.

Kind regards and thanks,

Andreas ;)

**Comment by robiso** [comment]
This will be available with the next update 3.4.3, which should be published within the next few days.
You will be able to set the html lang parameter to anything (configurable for admins and visitors seperately) in the Settings - Security. :)

**Comment by robiso** [comment]
To take into effect, please change the following in your theme (after we release WonderCMS 3.4.3)
- <html lang="<?= $Wcms->getSiteLanguage() ?>">

**Comment by WebCrew** [comment]
What is the "following" I can not see anything :)

**Comment by robiso** [comment]
Forgot the code block so it didn’t show the code, don’t use this yet until we release the new version :)

**Comment by WebCrew** [comment]
Ok thanks you very much :)

**Comment by robiso** [comment]
Closing issue, since this was release with 3.4.3 moments ago. :) Feel free to use this new functionality.

**Comment by joho1968** [comment]
Just a quick question: Where is this editable via the admin interface? I can see it working by modifying `database.js` directly, but I can't seem to find any option for it in the admin section.
