### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by storyandfortune** [WonderCMS/wondercms#303]
I get the following Fatal Error after unzipping.

Fatal error: Uncaught Exception: Could write to data folder. in /Users/chilelimemango/Sites/local-rick-truhls/index.php:428 Stack trace: #0 /Users/chilelimemango/Sites/local-rick-truhls/index.php(894): Wcms->checkFolder('/Users/chilelim...') #1 /Users/chilelimemango/Sites/local-rick-truhls/index.php(106): Wcms->getDb() #2 /Users/chilelimemango/Sites/local-rick-truhls/index.php(14): Wcms->__construct() #3 {main} thrown in /Users/chilelimemango/Sites/local-rick-truhls/index.php on line 428

running on PHP Version 8.1.16

**Comment by Jan69** [comment]
did you [correct file permissions to 644 and folder permissions to 755](https://github.com/WonderCMS/wondercms/wiki/500-internal-server-error) (and possibly [Give correct ownership of the directory where WonderCMS is installed](https://github.com/WonderCMS/wondercms/wiki/Other-errors), most likely `www-data`) ?
it certainly sounds like simply wrong file/folder permissions to me, with a typo in the error message

**Comment by storyandfortune** [comment]
Yeah. I even tried correcting everything to 777 the install would just never complete all the way.

**Comment by storyandfortune** [comment]
Just tried again…

**Comment by robiso** [comment]
@storyandfortune this is almost surely related to write permissions for your user.
Do you own the host yourself? If not, I would suggest you contact your hosting provider, since this is not a WonderCMS issue, but rather than a PHP configuration with permissions.

**Comment by storyandfortune** [comment]
I’m running on local host. Could be my install of PHP?

**Comment by robiso** [comment]
This might be helpful: https://duplicator.com/knowledge-base/how-to-fix-file-permissions-issues/

The issue could be that PHP does not have permissions. It might also take some trial and error.

As previously stated by @Jan69, make sure that: the correct ownership of folder is www-data. You can also do some Googling if you need help on how to do that.
