### ISSUE TITLE
[Feature Request] Per page theming/multiple active themes

### ISSUE THREAD

**Issue by dennimoto** [WonderCMS/wondercms#305]
I'd like to see a way to set themes independently per page, or extend themes to have multiple selectable styles.

For example:
The home landing page has a large CTA area and 3 column feature section, but a second page needs to be styled as a blog or similar with one large column and a sidebar sized column.

**Comment by joho1968** [comment]
Isn't that, technically speaking, a question for the actual theme in question?

You're welcome to provide some more details, and I'd be happy to see what I can do with my theme
(https://github.com/joho1968/wcms-bs5)
