### ISSUE TITLE
Backup a(nd Restore) Plugin?

### ISSUE THREAD

**Issue by Thatoo** [WonderCMS/wondercms#310]
It would be nice to have a plugin that could let the owner of a WonderCMS site to download a backup zip file of her/his website.
Backup would be already awesome (not having to use FTP everytime).
However, the user can restore if needed (quiet rare, much more than backuping) using FTP.

The best would be to be able to restore a zip file two thanks to the plugin but backuping would already be great!

**Comment by robiso** [comment]
Backing up your website is already possible through Settings - Backup and backup is downloadable in Settings - File.
However restoring is not possible at the moment, maybe in the future.

**Comment by Thatoo** [comment]
Sorry I missed it. It's awesome!
As I said, downloading backup is already great (just in case). Restoring backup is supposed to be rare and if that has to be thanks to FTP for now, be it.
WonderCMS is really full of nice surprise so far.
