### ISSUE TITLE
[Plugin improvement] Next/Previous on Blog Plugin

### ISSUE THREAD

**Issue by Thatoo** [WonderCMS/wondercms#311]
It would be really nice to have two automatic button added at the end of each blog post inviting to read either the next or previous article, ideally showing the title (and description) of next and previous article, not just writting "next" and "previous" on the button.

**Comment by robiso** [comment]
This is something for that be improved on the plugin itself, not completely WonderCMS-core related.

https://github.com/robiso/simple-blog/blob/master/class.SimpleBlog.php
Please feel free to open an issue here.
