### ISSUE TITLE
some question about image and  plugin of create blog

### ISSUE THREAD

**Issue by bluesky0341** [WonderCMS/wondercms#313]
The image does not have alt

Simple Blog
Adds a simple blog section to your WonderCMS website. Created by Stephan Stanisic.

how to revise  menu name blog into other name?

**Comment by bluesky0341** [comment]
could you help?

**Comment by robiso** [comment]
https://github.com/robiso/simple-blog/blob/master/class.SimpleBlog.php

Renaming it here (slug on line 6) should do it :)
