### ISSUE TITLE
php on a specific page

### ISSUE THREAD

**Issue by Vell61** [WonderCMS/wondercms#314]
Tell me how to place PHP code on a specific page, for example contact_form(), display a contact form (plugin) on the Contacts page (/contact)? Works only on Home...

**Comment by robiso** [comment]
@Vell61 

you can use an if statement and echo the contact form there in your template:

<?php
    if ($Wcms->currentPage == 'yourNewPage') {
    } else {
        echo the contact form
    }
?>
