### ISSUE TITLE
No Plugins or Themes - new installation

### ISSUE THREAD

**Issue by joetomasone** [WonderCMS/wondercms#317]
Trying to get WonderCMS up and running and I am finding that the plugins and themes pages have no plugins or themes on them, and I have no idea how to add a plugin.   Brand new install downloaded first from the WonderCMS site and then from Github - same problem each time. 

RHEL 9, Apache, PHP 8.0.30

Of note, I am getting a lot of "Cannot get content from url." messages with no further context.  
![chrome_POjYIUBcV4](https://github.com/WonderCMS/wondercms/assets/56984887/444e189a-970a-415c-a447-b4f0572352ee)

**Comment by robiso** [comment]
@joetomasone 

Can you please check if you have cURL enabled on your host?

We have had this issue reported in the past and the issue was due to cURL not being enabled.

The error message you are getting is due to the failed cURL call to fetch the themes/plugins for the first time (before caching them).

**Comment by joetomasone** [comment]
cURL is available:

[root@rhel9 html]# curl -V
curl 7.76.1 (x86_64-redhat-linux-gnu) libcurl/7.76.1 OpenSSL/3.0.7 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.10.4/openssl/zlib nghttp2/1.43.0
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
[root@rhel9 html]#

**Comment by joetomasone** [comment]
I updated the cURL as I noticed it was an older version:

[root@rhel9 html]# curl -V
curl 7.76.1 (x86_64-redhat-linux-gnu) libcurl/7.76.1 OpenSSL/3.0.7 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.10.4/openssl/zlib nghttp2/1.43.0
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
[root@rhel9 html]#

This did not fix the issue.

**Comment by joetomasone** [comment]
For more context:

Red Hat Enterprise Linux release 9.3 (Plow)
Linux rhel9.demo.local 5.14.0-362.18.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 3 15:54:45 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by joho1968** [comment]
Is the PHP cURL module installed, and its functions available?
